-- 1. ตาราง Personnel (ข้อมูลพนักงาน HR)
-- สร้างก่อนเพราะ profiles ต้องมาอ้างอิง
CREATE TABLE "personnel" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" text NOT NULL,
  "position" text NOT NULL,
  "created_at" timestamptz DEFAULT now()
  "status" smallint NOT NULL DEFAULT 0, -- -2=onleave, -1=suspend, 0=unauth, 1=active
);

-- 2. ตาราง Profiles (เชื่อมกับ auth.users ของ Supabase)
-- ใช้เก็บข้อมูล User ที่ไม่ใช่ Login credential
CREATE TABLE "profiles" (
  "id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  "username" text,
  "title" text,
  -- "role" smallint NOT NULL DEFAULT 0, -- 0=admin, 1=superadmin
  "personnel_id" bigint REFERENCES "personnel"("id"), -- เชื่อมกับพนักงาน
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  
  PRIMARY KEY ("id"),
  UNIQUE ("username")
);

-- 3. ตาราง Material Type
CREATE TABLE "material_type" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- 4. ตาราง Material
CREATE TABLE "material" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  "material_type_id" bigint NOT NULL REFERENCES "material_type"("id"),
  "quantity" integer NOT NULL DEFAULT 0,
  "unit" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- 5. ตาราง MR Form (ใบเบิก)
CREATE TABLE "mr_form" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject" text NOT NULL,
  "ref_no" text NOT NULL,
  "description" text, -- แก้ชื่อจาก descripts ให้สื่อความหมายขึ้น
  "date" timestamptz NOT NULL DEFAULT now(),
  "owing_to" text,
  
  -- Foreign Keys
  "creator_id" uuid NOT NULL REFERENCES "profiles"("id"), -- คนสร้างใบเบิก
  "authorizer_id" uuid REFERENCES "profiles"("id"), -- คนอนุมัติ (อาจจะยังไม่มีตอนสร้าง)
  "owner_personnel_id" bigint NOT NULL REFERENCES "personnel"("id"), -- เจ้าของเรื่อง (เชื่อมกับ personnel)
  
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

-- 6. ตาราง MR Form Materials (Junction Table รายการของในใบเบิก)
CREATE TABLE "mr_form_materials" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mr_form_id" bigint NOT NULL REFERENCES "mr_form"("id") ON DELETE CASCADE,
  "material_id" bigint NOT NULL REFERENCES "material"("id"),
  "quantity" integer NOT NULL
);

-- Comments
COMMENT ON TABLE "profiles" IS 'User profiles linked to auth.users. role: 0=user, 1=admin';
COMMENT ON TABLE "mr_form_materials" IS 'Items requested in the MR form';
